Django-Web/kof_database/database/urls.py
from django.urls import path

from . import views

app_name = 'database'
urlpatterns = [
    path('', views.index, name='index'),
    path('signUp/', views.signUp, name='signUp'),
]

Django-Web/kof_database/kof_database/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('database.urls')),
    path('admin/', admin.site.urls),

]

Django-Web/kof_database/database/models.py
from django.db import models

# Create your models here.
class Player(models.Model):
    email = models.CharField(max_length=100, primary_key=True)
    nickname = models.CharField(max_length=100)
    password = models.CharField(max_length=50)
    victories = models.IntegerField()
    defeats = models.IntegerField()
    country = models.CharField(max_length=50)

class Championship(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    dateStart = models.DateField()
    dateEnd = models.DateField()
    

class Game_version(models.Model):
	id = models.IntegerField(primary_key=True)
	year = models.IntegerField()
	version = models.CharField(max_length=100)

class Characters(models.Model):
	id = models.IntegerField(primary_key=True)
	name = models.CharField(max_length=50)
	game = models.ForeignKey(Game_version, on_delete=models.CASCADE)
	picked = models.IntegerField()
	round_win = models.IntegerField()
	round_loss = models.IntegerField()

class Team(models.Model):
	id = models.IntegerField(primary_key=True)
	characters = models.ManyToManyField(Characters)

class Matches(models.Model):
	id = models.IntegerField(primary_key=True)
	players = models.ManyToManyField(Player)

class Round_Score(models.Model):
	team_id = models.ForeignKey(Team, on_delete=models.CASCADE)
	char_id = models.ForeignKey(Characters, on_delete=models.CASCADE)
	roundWin = models.IntegerField()
	roundDefeated = models.IntegerField()
		
class Podium(models.Model):
	championship_id = models.ForeignKey(Championship, on_delete=models.CASCADE)
	player_id = models.ForeignKey(Player, on_delete=models.CASCADE)
	playerPosition = models.IntegerField()

Django-Web/kof_database/database/forms.py
from django.forms import ModelForm
from database.models import Player


class PlayerForm(ModelForm):
	
	class Meta:
		model = Player
		fields = '__all__'
		

Django-Web/kof_database/database/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from database.models import Player
import logging

logger = logging.getLogger(__name__)

# Create your views here.

def index(request):
	template = loader.get_template('database/index.html')
	context = {}
	return HttpResponse(template.render(context, request))

def signUp(request):
	try:
		pEmail = request.POST['email']
		pNick = request.POST['nickname']
		pPassw = request.POST['password']
		pRepassw = request.POST['repeat-password']
		logger.error('-' + pRepassw + '-')
		logger.error('-' + pPassw + '-')
		pCountry = request.POST['country']
		if pPassw == pRepassw:
			logger.error('senha confere')
			p = Player(email = pEmail, nickname = pNick, password = pPassw, victories = 0, defeats = 0, country = pCountry)
			p.save()
		else:
			logger.error('senha errada')
	except:
		logger.error('Theres is no nickname')
	template = loader.get_template('database/signUp.html')
	context = {}
	return HttpResponse(template.render(context, request))

Django-Web/kof_database/database/templates/database/base.html
<!DOCTYPE html>
<html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/flag-icon.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static '/css/select-sim.css' %}" />
<style type="text/css">

form{
    margin-top: 50px;
}

footer{
    position:fixed;
    color: white;
    bottom:0px;
    width:100%;
    text-align: left;
}

@font-face {
    font-family: rabbit;
    src: url({% static "fonts/KGNeatlyPrinted.ttf" %});
}

body{
    background-color: rgb(39,42,51);
}

.container{
    font-family: 'Roboto', sans-serif;
    font-size: 14px;
    font-weight: bold;
    color: white;
}

input{
    border: 1px solid #ff0000;
    border-radius: 15px;
    padding: 0px 10px 0px 10px;
    background-color: rgb(0,0,0);
}

.myNavbar{
    background:  #000;
    text-align: left;
    color: #fff;
    font-family: 'Roboto', sans-serif;
    font-size: 20px;
    padding-left: 2%;
    vertical-align: baseline;
    padding-top: 5px;
}

.loginButton{
    float: right;
    font-size: 15px;
    margin-right: 2%;
    padding: 25px 20px;
}

.aLink{
    cursor:pointer;
    color: #fff;
    text-decoration: none;
}

.aLink:hover{
    color: #ff0000;
    text-decoration: none;
}

.advertisingText{
    font-family: 'Roboto', sans-serif;
    font-size: 20px;
    padding: 10px;
}

.container{
    text-align: center;
}



.navRow{
    margin-right:-15px;
    margin-left:-15px;
    margin-bottom: 10px;
}

</style>
<head>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/dropdown.css' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="shortcut icon" href="https://vignette.wikia.nocookie.net/snk/images/6/67/The_king_of_fighters_xiv_kof_xiv_logo_3_png_by_zeref_ftx-dadviaf.png/revision/latest?cb=20170617161334">
<title>KoF Ranking</title>
</head>
<body style="background-color: rgb(39,42,51)">
    <div class="myNavbar">
        <div class="navRow">
            <b><a style="text-decoration: none;" href="{% url 'database:index' %}"><img width="100px" src="{% static 'arcade_logo.png' %}"></a></b>
            <div class="loginButton">
                    <a style="text-decoration: none; color: white;" href="{% url 'database:signUp' %}"><input type="button" name="Login" value="Login"></input></a>
            </div>
        </div>
    </div>
<div class="container">
{% block content%}{% endblock%}
</div>
</body>
<footer>
    v0.1a
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

{% block jScript %}
{% endblock %}
</html>